(function(){
  const cfg=window.URBAN_TREND_SUPABASE;
  if(!cfg||!window.supabase){console.error('Supabase no está disponible');return}
  const client=window.supabase.createClient(cfg.url,cfg.anonKey);
  const keys={services:'ut_services_v3',products:'ut_products_v3',bookings:'ut_bookings_v3',cart:'ut_cart_v3',photos:'ut_photos_v3',config:'ut_config_v3',profiles:'ut_profiles_v1',history:'ut_history_v1',orders:'ut_orders_v1'};
  let ready=false,session=null,syncing=false;
  const save=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  const publicImage=path=>client.storage.from('gallery').getPublicUrl(path).data.publicUrl;
  const serviceToLocal=x=>({id:x.id,name:x.name,duration:x.duration,price:Number(x.price),durationMinutes:x.duration_minutes,activeMinutes:x.active_minutes,waitMinutes:Number(x.wait_minutes||0),cycles:Number(x.cycles||1),finalActiveMinutes:Number(x.final_active_minutes||0),bufferMinutes:Number(x.buffer_minutes||0),allowsOverbooking:Boolean(x.allows_overbooking),safetyCategory:x.safety_category||'',repeatWaitDays:Number(x.repeat_wait_days||0),safetyMessage:x.safety_message||''});
  const productToLocal=x=>({id:x.id,sku:x.sku||'',name:x.name,brand:x.brand||'',model:x.model||'',variant:x.variant||'',color:x.color_tone||'',desc:x.description||'',tag:x.category||'General',cost:x.cost==null?'':Number(x.cost),price:Number(x.price),stock:Number(x.stock),minStock:Number(x.min_stock??3),supplier:x.supplier||'',barcode:x.barcode||'',notes:x.notes||''});
  const bookingToLocal=x=>({id:x.id,name:x.customer_name,surname:x.customer_surname||'',phone:x.phone,service:x.service_name,date:x.booking_date,time:String(x.booking_time).slice(0,5),notes:x.notes||'',status:x.status,termsAcceptedAt:x.terms_accepted_at,contactId:x.contact_id||'',profileId:x.profile_id||'',safetyOverride:Boolean(x.safety_override),safetyOverrideReason:x.safety_override_reason||''});
  const bookingToCloud=x=>({id:x.id,customer_name:x.name,customer_surname:x.surname||'',phone:x.phone||'',service_name:x.service,booking_date:x.date,booking_time:x.time,notes:x.notes||'',status:x.status||'Pendiente',terms_accepted_at:x.termsAcceptedAt||new Date().toISOString(),contact_id:x.contactId||null,profile_id:x.profileId||null,safety_override:Boolean(x.safetyOverride),safety_override_reason:x.safetyOverrideReason||''});
  function rerender(){try{services=JSON.parse(localStorage.getItem(keys.services)||'[]');products=JSON.parse(localStorage.getItem(keys.products)||'[]')}catch{};try{renderServices();renderProducts();window.renderUrbanGallery?.();window.renderUrbanAdmin?.();window.applyUrbanConfig?.()}catch(error){console.error('No se pudo actualizar la vista',error)} }
  async function loadPublic(){
    const [s,p,g,c]=await Promise.all([client.from('services').select('*').eq('active',true).order('sort_order'),client.from('products').select('*').eq('active',true).order('name'),client.from('gallery').select('*').eq('active',true).order('sort_order'),client.from('business_settings').select('*').eq('id','main').maybeSingle()]);
    if(!s.error&&s.data?.length)save(keys.services,s.data.map(serviceToLocal));
    if(!p.error&&p.data?.length)save(keys.products,p.data.map(productToLocal));
    if(!g.error)save(keys.photos,(g.data||[]).map(x=>({id:x.id,title:x.title,data:publicImage(x.image_path),path:x.image_path})));
    if(!c.error&&c.data)save(keys.config,{name:c.data.name,whatsapp:c.data.whatsapp,phone:c.data.phone,email:c.data.email,address:c.data.address,hours:c.data.hours,mapsUrl:c.data.maps_url||'',facebookUrl:c.data.facebook_url||'',instagramUrl:c.data.instagram_url||'',pickupCutoff:String(c.data.pickup_cutoff||'').slice(0,5),nextDayPickupFrom:String(c.data.next_day_pickup_from||'').slice(0,5),developerName:c.data.developer_name||'',developerUrl:c.data.developer_url||''});
  }
  async function loadPrivate(){if(!session)return;const [b,p,h,o]=await Promise.all([client.from('bookings').select('*').order('booking_date').order('booking_time'),client.from('customer_profiles').select('id,contact_id,display_name,relationship,birth_date,active,contacts(phone)').order('display_name'),client.from('service_history').select('*').order('performed_on',{ascending:false}),client.from('orders').select('*,order_items(*)').order('created_at',{ascending:false})]);if(!b.error)save(keys.bookings,(b.data||[]).map(bookingToLocal));if(!p.error)save(keys.profiles,(p.data||[]).map(x=>({id:x.id,contactId:x.contact_id,name:x.display_name,relationship:x.relationship||'',birthDate:x.birth_date||'',active:x.active,phone:x.contacts?.phone||''})));if(!h.error)save(keys.history,(h.data||[]).map(x=>({id:x.id,profileId:x.profile_id,bookingId:x.booking_id||'',serviceId:x.service_id||'',service:x.service_name,safetyCategory:x.safety_category||'',date:x.performed_on,notes:x.notes||''})));if(!o.error)save(keys.orders,o.data||[])}
  async function isAdmin(){if(!session)return false;const {data,error}=await client.rpc('is_urban_admin');return !error&&data===true}
  async function login(email,password){const cleanEmail=String(email||'').trim().toLowerCase();if(!cleanEmail||!password)return {ok:false,message:'Completá correo y contraseña'};const {data,error}=await client.auth.signInWithPassword({email:cleanEmail,password});if(error)return {ok:false,message:error.message||'No se pudo iniciar sesión'};session=data.session;if(!await isAdmin()){await client.auth.signOut();session=null;return {ok:false,message:'La cuenta no está autorizada como administradora'}}await loadPrivate();rerender();return {ok:true}}
  async function logout(){await client.auth.signOut();session=null}
  async function replaceRows(table,rows){if(!session)return;const existing=await client.from(table).select('id'),ids=rows.map(x=>x.id);if(existing.data){const remove=existing.data.map(x=>x.id).filter(id=>!ids.includes(id));if(remove.length)await client.from(table).delete().in('id',remove)}if(rows.length){const result=await client.from(table).upsert(rows);if(result.error)throw result.error}}
  async function sync(key,value){if(!ready||syncing)return;syncing=true;try{
    if(key===keys.services)await replaceRows('services',value.map((x,i)=>({id:x.id,name:x.name,duration:x.duration,price:Number(x.price),duration_minutes:x.durationMinutes||null,active_minutes:x.activeMinutes||null,wait_minutes:Number(x.waitMinutes||0),cycles:Number(x.cycles||1),final_active_minutes:Number(x.finalActiveMinutes||0),buffer_minutes:Number(x.bufferMinutes||0),allows_overbooking:Boolean(x.allowsOverbooking),safety_category:x.safetyCategory||'',repeat_wait_days:Number(x.repeatWaitDays||0),safety_message:x.safetyMessage||'',active:true,sort_order:i})));
    if(key===keys.products)await replaceRows('products',value.map(x=>({id:x.id,sku:x.sku||null,name:x.name,brand:x.brand||'',model:x.model||'',variant:x.variant||'',color_tone:x.color||'',description:x.desc||'',category:x.tag||'General',cost:x.cost===''||x.cost==null?null:Number(x.cost),price:Number(x.price),stock:Number(x.stock),min_stock:Number(x.minStock??3),supplier:x.supplier||'',barcode:x.barcode||'',notes:x.notes||'',active:true})));
    if(key===keys.bookings){if(session)await replaceRows('bookings',value.map(bookingToCloud));else if(value.length){const row=bookingToCloud(value[value.length-1]);const result=await client.from('bookings').insert(row);if(result.error)throw result.error}}
    if(key===keys.config&&session){const x=value;await client.from('business_settings').upsert({id:'main',name:x.name,whatsapp:x.whatsapp,phone:x.phone,email:x.email,address:x.address,hours:x.hours,maps_url:x.mapsUrl||'',facebook_url:x.facebookUrl||'',instagram_url:x.instagramUrl||'',pickup_cutoff:x.pickupCutoff||null,next_day_pickup_from:x.nextDayPickupFrom||null,developer_name:x.developerName||'',developer_url:x.developerUrl||'',updated_at:new Date().toISOString()})}
    if(key===keys.photos&&session)await syncPhotos(value);
  }catch(error){console.error('No se pudo sincronizar',error);window.notify?.('Cambio guardado localmente; falta sincronizar')}finally{syncing=false}}
  async function dataUrlBlob(data){return(await fetch(data)).blob()}
  async function checkSafety(phone,displayName,serviceId){const {data,error}=await client.rpc('safety_result',{p_phone:phone,p_display_name:displayName,p_service_id:serviceId});if(error)return {blocked:false,available:false,message:'El control preventivo todavía no está activado.'};return {...data,available:true}}
  async function getAvailability(date,serviceId){if(!date||!serviceId)return {ok:true,slots:[]};const {data,error}=await client.rpc('available_slots',{p_date:date,p_service_id:serviceId});if(error)return {ok:false,slots:[],message:error.message};return {ok:true,slots:(data||[]).map(x=>String(x.slot_time).slice(0,5))}}
  async function loadSchedule(){if(!session)return {ok:false};const [hours,blocks,settings]=await Promise.all([client.from('business_hours').select('*').order('day_of_week'),client.from('schedule_blocks').select('*').gte('ends_at',new Date().toISOString()).order('starts_at'),client.from('business_settings').select('schedule_ready').eq('id','main').maybeSingle()]);if(hours.error||blocks.error)return {ok:false,message:hours.error?.message||blocks.error?.message};return {ok:true,hours:hours.data||[],blocks:blocks.data||[],ready:Boolean(settings.data?.schedule_ready)}}
  async function saveSchedule(hours){if(!session)return {ok:false,message:'Acceso no autorizado'};const {error}=await client.rpc('save_business_hours',{p_hours:hours});return error?{ok:false,message:error.message}:{ok:true}}
  async function addScheduleBlock(block){if(!session)return {ok:false,message:'Acceso no autorizado'};const {error}=await client.from('schedule_blocks').insert({starts_at:block.startsAt,ends_at:block.endsAt,reason:block.reason||'',created_by:session.user.id});return error?{ok:false,message:error.message}:{ok:true}}
  async function deleteScheduleBlock(id){if(!session)return {ok:false,message:'Acceso no autorizado'};const {error}=await client.from('schedule_blocks').delete().eq('id',id);return error?{ok:false,message:error.message}:{ok:true}}
  async function createPayment(order){const {data,error}=await client.functions.invoke('create-payment',{body:order});if(error)return {ok:false,message:error.message||'No se pudo iniciar el pago'};return data}
  async function updateOrderStatus(id,status){if(!session)return {ok:false,message:'Acceso no autorizado'};const {error}=await client.from('orders').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(!error){await loadPrivate();rerender()}return error?{ok:false,message:error.message}:{ok:true}}
  async function requestBooking(booking,serviceId){const {data,error}=await client.rpc('request_booking_v2',{p_id:booking.id,p_display_name:`${booking.name} ${booking.surname||''}`.trim(),p_phone:booking.phone,p_service_id:serviceId,p_booking_date:booking.date,p_booking_time:booking.time,p_notes:booking.notes||'',p_terms_accepted_at:booking.termsAcceptedAt});if(error)return {ok:false,message:error.message||'No se pudo solicitar el turno'};if(data?.ok){await loadPrivate();rerender()}return data}
  async function adminRequestBooking(booking,serviceId,overrideReason=''){const {data,error}=await client.rpc('admin_request_booking',{p_id:booking.id,p_display_name:`${booking.name} ${booking.surname||''}`.trim(),p_phone:booking.phone,p_service_id:serviceId,p_booking_date:booking.date,p_booking_time:booking.time,p_notes:booking.notes||'',p_override_reason:overrideReason});if(error)return {ok:false,message:error.message||'No se pudo guardar el turno'};if(data?.ok){await loadPrivate();rerender()}return data}
  async function saveProfile(profile){if(!session||!await isAdmin())return {ok:false,message:'Acceso no autorizado'};let contactId=profile.contactId;if(!contactId){const phone=String(profile.phone||'').trim(),found=await client.from('contacts').select('id').eq('phone_normalized',phone.replace(/\D/g,'')).maybeSingle();if(found.error)return {ok:false,message:found.error.message};if(found.data)contactId=found.data.id;else{const made=await client.from('contacts').insert({phone}).select('id').single();if(made.error)return {ok:false,message:made.error.message};contactId=made.data.id}}const row={contact_id:contactId,display_name:profile.name,relationship:profile.relationship||'',birth_date:profile.birthDate||null,active:true};const result=profile.id?await client.from('customer_profiles').update(row).eq('id',profile.id):await client.from('customer_profiles').insert(row);if(result.error)return {ok:false,message:result.error.message};await loadPrivate();rerender();return {ok:true}}
  async function saveHistory(item){if(!session||!await isAdmin())return {ok:false,message:'Acceso no autorizado'};const service=JSON.parse(localStorage.getItem(keys.services)||'[]').find(x=>x.id===item.serviceId);const result=await client.from('service_history').insert({profile_id:item.profileId,service_id:item.serviceId||null,service_name:service?.name||item.service,safety_category:service?.safetyCategory||'',performed_on:item.date,notes:item.notes||'',created_by:session.user.id});if(result.error)return {ok:false,message:result.error.message};await loadPrivate();rerender();return {ok:true}}
  async function syncPhotos(photos){
    const cloud=await client.from('gallery').select('*'),keep=[];
    for(let i=0;i<photos.length;i++){const photo=photos[i];let path=photo.path;if(!path&&String(photo.data).startsWith('data:')){path=`trabajos/${photo.id}.jpg`;const upload=await client.storage.from('gallery').upload(path,await dataUrlBlob(photo.data),{contentType:'image/jpeg',upsert:true});if(upload.error)throw upload.error;photo.path=path;photo.data=publicImage(path)}keep.push({id:photo.id,title:photo.title,image_path:path,sort_order:i,active:true})}
    const remove=(cloud.data||[]).filter(x=>!keep.some(k=>k.id===x.id));if(remove.length){await client.storage.from('gallery').remove(remove.map(x=>x.image_path));await client.from('gallery').delete().in('id',remove.map(x=>x.id))}if(keep.length)await client.from('gallery').upsert(keep);save(keys.photos,photos)
  }
  async function init(){const auth=await client.auth.getSession();session=auth.data.session;if(await isAdmin()){sessionStorage.setItem('ut_admin_session','1');await loadPrivate()}else{sessionStorage.removeItem('ut_admin_session');if(session){await client.auth.signOut();session=null}}await loadPublic();ready=true;rerender()}
  client.auth.onAuthStateChange(async(event,newSession)=>{if(event!=='PASSWORD_RECOVERY')return;session=newSession;const password=prompt('Escribí tu nueva contraseña (mínimo 8 caracteres):');if(!password)return;if(password.length<8){alert('La contraseña debe tener al menos 8 caracteres. Volvé a solicitar el enlace.');return}const {error}=await client.auth.updateUser({password});if(error){alert(`No se pudo actualizar: ${error.message}`);return}alert('Contraseña actualizada. Ya podés ingresar con tu correo y la nueva contraseña.');history.replaceState({},document.title,location.pathname);await client.auth.signOut();session=null;sessionStorage.removeItem('ut_admin_session');rerender()});
  window.urbanCloud={client,init,login,logout,sync,checkSafety,getAvailability,loadSchedule,saveSchedule,addScheduleBlock,deleteScheduleBlock,createPayment,updateOrderStatus,requestBooking,adminRequestBooking,saveProfile,saveHistory,refreshPrivate:loadPrivate};
  window.addEventListener('DOMContentLoaded',init);
})();
